<a href="https://colab.research.google.com/github/Muchee-ai/Data-preparation/blob/main/Data-prep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

dropna() - NaN qiymatlarni tashlab yuborish

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/automobile_data_nan.csv")
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [3]:
df.isnull() #mavjud bo'lmagan qiymatlarga TRUE qaytaradi

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,False,False,False,False,False,False,False,True,False,False
1,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...
56,False,False,False,False,False,False,False,False,False,False
57,False,False,False,True,False,True,False,False,False,False
58,False,False,False,False,True,False,False,False,True,False
59,False,False,False,False,False,True,False,False,False,False
60,False,False,False,False,False,False,False,True,False,False

In [4]:
df.notnull() #mavjud bo'lmagan qiymatlarga FALSE qaytaradi

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,True,True,True,True,True,True,True,False,True,True
1,True,True,True,False,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,False,True
3,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...
56,True,True,True,True,True,True,True,True,True,True
57,True,True,True,False,True,False,True,True,True,True
58,True,True,True,True,False,True,True,True,False,True
59,True,True,True,True,True,False,True,True,True,True
60,True,True,True,True,True,True,True,False,True,True

In [5]:
df.isnull().sum() #harbir ustundagi mavjud bo'lmagan qiymatlar

index                0
company              0
body-style           0
wheel-base          15
length              13
engine-type         12
num-of-cylinders     0
horsepower          16
average-mileage     15
price                3
dtype: int64

In [6]:
len(df) #dataFrame uzunligi

61

In [7]:
df.isnull().sum()/len(df)*100

index                0.000000
company              0.000000
body-style           0.000000
wheel-base          24.590164
length              21.311475
engine-type         19.672131
num-of-cylinders     0.000000
horsepower          26.229508
average-mileage     24.590164
price                4.918033
dtype: float64

In [8]:
df.dropna() #NaN qiymatga ega qatorlarni tashlab yuborish

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
14,17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
16,19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
19,28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
25,34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
28,37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
29,38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
41,54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
43,56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
51,69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0

In [9]:
len(df.dropna())

14

In [10]:
df.dropna(axis=1) #NaN qiymatli ustunlarni tashlab yuborish

    index      company   body-style num-of-cylinders
0       0  alfa-romero  convertible             four
1       1  alfa-romero  convertible             four
2       2  alfa-romero    hatchback              six
3       3         audi        sedan             four
4       4         audi        sedan             five
..    ...          ...          ...              ...
56     81   volkswagen        sedan             four
57     82   volkswagen        sedan             four
58     86   volkswagen        sedan             four
59     87        volvo        sedan             four
60     88        volvo        wagon             four

[61 rows x 4 columns]

In [11]:
df.dropna(axis=1, thresh=48) #48 tadan kam haqiqiy qiymatga ega (ya'ni NaN'lari ko'p) ustunlar o'chiriladi

,index,company,body-style,length,engine-type,num-of-cylinders,price
0,0,alfa-romero,convertible,168.8,dohc,four,13495.0
1,1,alfa-romero,convertible,168.8,dohc,four,16500.0
2,2,alfa-romero,hatchback,171.2,ohcv,six,16500.0
3,3,audi,sedan,176.6,ohc,four,13950.0
4,4,audi,sedan,176.6,ohc,five,17450.0
...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,171.7,ohc,four,7975.0
57,82,volkswagen,sedan,171.7,NaN,four,7995.0
58,86,volkswagen,sedan,NaN,ohc,four,9995.0
59,87,volvo,sedan,188.8,NaN,four,12940.0
60,88,volvo,wagon,188.8,ohc,four,13415.0

In [12]:
df.dropna(subset=['price', 'horsepower'], inplace=True) #faqat price va horsepower ustunini tekshirish
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
1,1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0

In [13]:

df.shape

(43, 10)

.fillna() - NaN qiymat to'ldirish

In [14]:
df.fillna(0, inplace=True) #barcha NaN qiymatlarni 0 bn to'ldirish
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
1,1,alfa-romero,convertible,0.0,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,0.0,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0

In [16]:
#df.fillna({'wheel-base':100}) #'wheel-base'ustunidagi NaN qiymatlarni 100ga tengladik

In [17]:

np.mean(df['wheel-base'])

np.float64(69.65813953488373)

In [22]:
df.fillna({'wheel-base':np.mean(df['wheel-base'])}), 'inplace=True' #ustundagi NaN qiymtlarni uni o'rta qiymati bn to'ldirish
df.head(10)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
1,1,alfa-romero,convertible,0.0,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,0.0,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
8,10,bmw,sedan,0.0,176.8,ohc,four,101.0,23.0,16925.0
9,11,bmw,sedan,101.2,176.8,ohc,six,121.0,0.0,20970.0
11,14,bmw,sedan,103.5,0.0,ohc,six,182.0,16.0,41315.0
12,15,bmw,sedan,110.0,197.0,ohc,six,182.0,0.0,36880.0
14,17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0

In [ ]:
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
1,1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0

In [ ]:
df.fillna(method='ffill', inplace=True) #NaN qiymatga ega ma'lumotni unda oldingi qiymat bn tenglash
df.head()

/tmp/ipykernel_640/2766238617.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
1,1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0

In [ ]:
df.fillna(method='bfill', inplace=True) #NaN qiymatga ega ma'lumotni unda keyingi qiymat bn tenglash
df.head()

/tmp/ipykernel_640/3551656406.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', inplace=True)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
1,1,alfa-romero,convertible,94.5,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0

In [38]:
df2 = df[df.company == 'alfa-romero'].copy()
cols = ['wheel-base', 'average-mileage']
df2[cols] = df2[cols].replace(0, np.nan).bfill().ffill()
df2 #jadvalda qiymatlarni brinchi 0.0 dan nan qiymatga o'tkazildi va faqatgina 'alfa-romero'ustunlarini chaqirib ularni nan qiymatlari to'ldirildi

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
1,1,alfa-romero,convertible,94.5,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0

df[df.company=='alfa-romero'].fillna(method='bfill')

[agar brdaniga aynan 'alfa-romero'ustunlarini chaqirib ularga qiymat bermoqchi bo'lsak]

  QIYMATLARNI O'ZGARTIRISH